-- SUPERSEDED: Do not run this file.
-- The authoritative implementation is the versioned migration created by:
--   supabase migration new security_remediation
-- Apply and verify that migration in a non-production project first.
--
-- Historical note: this draft described the initial payment-event and YooKassa
-- setup. The versioned security-remediation migration is the reviewed source
-- for payment idempotency and server-only permissions.
