-- SUPERSEDED: Do not run this file.
-- The authoritative implementation is the versioned migration created by:
--   supabase migration new security_remediation
-- Apply and verify that migration in a non-production project first.
--
-- Historical note: this pre-remediation hardening draft described legacy
-- browser-facing access controls. The versioned security-remediation migration
-- replaces it with the reviewed reservation and function-permission model.
