-- SUPERSEDED: Do not run this file.
-- The authoritative implementation is the versioned migration created by:
--   supabase migration new security_remediation
-- Apply and verify that migration in a non-production project first.
--
-- Historical note: this draft described the retired direct story-finalisation
-- RPC. The versioned security-remediation migration replaces that flow with
-- server-only reservation and finalisation controls.
